---
- name: Cleanup Legacy logstash
  hosts: log_hosts
  user: root
  gather_facts: no
  handlers:
    - name: Restart RAX-MaaS
      service:
        name: rackspace-monitoring-agent
        state: restarted
  pre_tasks:
    - name: Ensure ansible fact directory exists
      file:
        path: "/etc/ansible/facts.d"
        state: directory

    - name: Set cleanup fact
      ini_file:
        dest: "/etc/ansible/facts.d/mtc.fact"
        section: "cleanup"
        option: "initialized"
        value: true

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"
      tags:
        - always

    - name: GET cluster status
      uri:
        url: "http://127.0.0.1:9600/?pretty"
        method: GET
        status_code: 200
        return_content: yes
      register: logstash_status
      until: logstash_status is success
      retries: 6
      delay: 5
      failed_when: false

    - name: Exit block
      block:
        - name: Set cleanup fact
          ini_file:
            dest: "/etc/ansible/facts.d/mtc.fact"
            section: "cleanup"
            option: "logstash"
            value: true

        - name: End playbook if the system has been cleaned
          meta: end_play
      when:
        - ((ansible_local['mtc']['cleanup']['logstash'] is defined) and
           (ansible_local['mtc']['cleanup']['logstash'] | bool)) or
          ((logstash_status.json is defined) and
           (logstash_status.json.version is version('6.0.0', '>=')))
  tasks:
    - name: (LOGSTASH) Remove old maas checks
      find:
        paths: /etc/rackspace-monitoring-agent.conf.d
        file_type: file
        patterns: "*logstash*"
      register: logstash_checks

    - name: (LOGSTASH) Remove old maas checks
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ logstash_checks.files }}"
      notify:
        - Restart RAX-MaaS

    - name: (LOGSTASH) Remove old beat
      package:
        name: logstash
        state: absent
  post_tasks:
    - name: Set cleanup fact
      ini_file:
        dest: "/etc/ansible/facts.d/mtc.fact"
        section: "cleanup"
        option: "logstash"
        value: true
