---
- name: Cleanup Legacy kibana
  hosts: log_hosts
  user: root
  gather_facts: no
  handlers:
    - name: Restart RAX-MaaS
      service:
        name: rackspace-monitoring-agent
        state: restarted
  pre_tasks:
    - name: Ensure ansible fact directory exists
      file:
        path: "/etc/ansible/facts.d"
        state: directory

    - name: Set cleanup fact
      ini_file:
        dest: "/etc/ansible/facts.d/mtc.fact"
        section: "cleanup"
        option: "initialized"
        value: true

    - name: Refresh local facts
      setup:
        filter: ansible_local
        gather_subset: "!all"
      tags:
        - always

    - name: GET cluster status
      uri:
        url: "http://127.0.0.1:5601/api/status"
        method: GET
        status_code: 200
        return_content: yes
      register: kibana_status
      until: kibana_status is success
      retries: 6
      delay: 5
      failed_when: false

    - name: Exit block
      block:
        - name: Set cleanup fact
          ini_file:
            dest: "/etc/ansible/facts.d/mtc.fact"
            section: "cleanup"
            option: "kibana"
            value: true

        - name: End playbook if the system has been cleaned
          meta: end_play
      when:
        - ((ansible_local['mtc']['cleanup']['kibana'] is defined) and
           (ansible_local['mtc']['cleanup']['kibana'] | bool)) or
          ((kibana_status.json is defined) and
           (kibana_status.json.version.number is version('6.0.0', '>=')))
  tasks:
    - name: (KIBANA) Remove old maas checks
      find:
        paths: /etc/rackspace-monitoring-agent.conf.d
        file_type: file
        patterns: "*kibana*"
      register: kibana_checks

    - name: (KIBANA) Remove old maas checks
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ kibana_checks.files }}"
      notify:
        - Restart RAX-MaaS

    - name: (KIBANA) Stop old beat
      service:
        name: apache2
        state: stopped
      ignore_errors: true

    - name: (KIBANA) Remove old beat
      package:
        name: apache2
        state: absent
  post_tasks:
    - name: Set cleanup fact
      ini_file:
        dest: "/etc/ansible/facts.d/mtc.fact"
        section: "cleanup"
        option: "kibana"
        value: true
