---
## Usage create a set of variables that the tools team will use for our deployments.
## This will create
##   - proxy environment options options when "http_proxy_server" is defined. The no proxy configuration is optional.
##   - haproxy configurations for our internal tooling
##   - beat service state options
##
## Playbook options:
##  - "http_proxy_server" (OPTIONAL)
##  - "https_proxy_server" (OPTIONAL)
##  - "extra_no_proxy_hosts" (OPTIONAL)
##  - "java_http_proxy" (OPTIONAL)
##  - "java_https_proxy_port" (OPTIONAL)
##  - "java_https_proxy" (OPTIONAL)
##  - "java_https_proxy_port" (OPTIONAL)
##  - "var_location" (OPTIONAL) variable directory path
##  - "file_location" (OPTIONAL) variable file path
##
## When defining a proxy, the http(s)_proxy_server variables must be in the form of a URL with a specified port.

# USAGE:$ (openstack-ansible || ansible-playbook) generate-environment-vars.yml -e 'http_proxy_server=https://proxy_server.local:3128'

- name: Create user tools variables file
  hosts: localhost
  connection: local
  user: root
  gather_facts: no
  vars:
    http_proxy_server: "none://none:none"
    java_http_proxy: "{{ (http_proxy_server).split(':')[1].strip('/') }}"
    java_https_proxy: "{{ (https_proxy_server | default(http_proxy_server)).split(':')[1].strip('/') }}"
    java_http_proxy_port: "{{ (http_proxy_server).split(':')[2].strip('/') }}"
    java_https_proxy_port: "{{ (https_proxy_server | default(http_proxy_server)).split(':')[2].strip('/') }}"
    no_proxy_hosts:
      - localhost
      - 127.0.0.1
      - "{{ internal_lb_vip_address }}"
      - "{{ external_lb_vip_address }}"
      - "{{ ((groups['rabbitmq_all'] | default([])) | union((groups['log_containers'] | default([])))) | map('extract', hostvars, 'ansible_host') | list | join(',') }}"
    all_var_location:
      osa: "/etc/openstack_deploy"
      osp: "/home/stack"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Check OSP
      stat:
        path: "/etc/rhosp-release"
      register: osp_check

    - name: Check OSA
      stat:
        path: "/etc/openstack-release"
      register: osa_check

    - name: Set variable path location
      set_fact:
        var_location: "{{ all_var_location['osa'] }}"
      when:
        - osa_check.stat.exists | bool

    - name: Set variable path location
      set_fact:
        var_location: "{{ all_var_location['osp'] }}"
      when:
        - osp_check.stat.exists | bool

    - name: Setup exit
      block:
        - name: Break point notice
          debug:
            msg: >-
              No Known deployment configuration has been detected. No variables
              will be generated.

        - name: End play if no known deployment configuration is detected
          meta: end_play
      when:
        - var_location is undefined

    - name: State config directory
      stat:
        path: "{{ var_location }}"
      register: config_dir

    - name: Ensure openstack-deploy directory exists
      file:
        path: "{{ var_location }}"
        state: directory
      when:
        - not config_dir.stat.exists | bool

    - name: Create user_tools_variables.yml
      template:
        src: templates/user_tools_variables.yml.j2
        dest: "{{ file_location | default(var_location + '/user_tools_variables.yml') }}"

    - name: Create mtc.rc
      template:
        src: templates/mtc.rc.j2
        dest: "{{ lookup('env', 'HOME') }}/.mtc.rc"
      when:
        - http_proxy_server != 'none://none:none'

    - name: Run RPC setup with OpenStack-Ansible
      include_tasks: common-tasks/setup_rpc.yml
      vars:
        var_psth: "{{ var_location }}"
      when:
        - osa_check.stat.exists | bool

    # - name: Run RPC setup with OSP
    #   include_tasks: common-tasks/setup_osp.yml  # unimplemented
    #   vars:
    #     var_psth: "{{ var_location }}"
    #   when:
    #     - osp_check.stat.exists | bool

    - name: Ensure secrets exist
      include_tasks: common-tasks/setup_secrets.yml
      vars:
        var_psth: "{{ var_location }}"
